=== thefightagainstmalware/malware-categorization-naming/malware-categorization.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": ["name", "other-names", "first-reported", "comment"],
    "properties": {
        "name": {
            "type": "string",
            "description": "Official name of this type of malware"
        },
        "comment": {
            "type": "string",
            "description": "Information about the malware"
        },
        "other-names": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Other names for this malware. After this convention is published, should not contain members unless the name is widespread and the official name disagrees"
        },
        "first-reported": {
            "type": ["null", "string"],
            "description": "The day the GitHub issue that added this was filed. Timezone is UTC, format is YY/MM/DD",
            "pattern": "^\\d\\d/(1[0-2]|0\\d)/([0-2]\\d|3[0-1])$"
        }
    }
}

=== thefightagainstmalware/malware-categorization-naming/macromodules/macromodules.json
{
    "$schema": "../malware-categorization.schema.json",
    "name": "Macromodules",
    "comment": "Macromodules grabber grabs Minecraft info. Generally consists of 3 classes, the Mod class, which calls the Stealer Class. The stealer class is a Gelox discord webhook class",
    "first-reported": null,
    "other-names": []
}

=== thefightagainstmalware/malware-categorization-naming/kodeine/kodeine.json
{
    "$schema": "../malware-categorization.schema.json",
    "name": "Kodeine",
    "comment": "Kodeine is a stealer which uses reflection to gain access to all of the session fields. Also steals Discord info. Uses a pastebin or GitHub gist to store Discord webhooks.",
    "other-names": [
        "Sir Kodeine",
        "abcd"
    ],
    "first-reported": null
}

=== thefightagainstmalware/malware-categorization-naming/neorat/neorat.json
{
    "$schema": "../malware-categorization.schema.json",
    "name": "NeoRat",
    "comment": "NeoRat grabs information from the blackboard or from the Pizza Client token, endpoint is a heroku webapp.",
    "first-reported": null,
    "other-names": [
        "Essentials",
        "Essentials.loadExtensions"
    ]
}

=== thefightagainstmalware/malware-categorization-naming/typetools/typetools.json
{
    "$schema": "../malware-categorization.schema.json",
    "name": "typetools",
    "comment": "Malware which uses several classes for payloads. Steals Discord, MC, and other pieces of information",
    "first-reported": null,
    "other-names": [
        "jodah",
        "Ben",
        "Yoink"
    ]
}

=== thefightagainstmalware/malware-categorization-naming/razebator/razebator.json
{
    "$schema": "../malware-categorization.schema.json",
    "name": "Razebator",
    "comment": "Razebator is a grabber which is often bundled with BazaarNotifier in its package, and the grabber class is normally CraftingModule. Steals Minecraft tokens",
    "other-names": [
        "TURKIE",
        "bn"
    ],
    "first-reported": null
}
